import { Hotel } from '../model'

export const hotelList: Hotel[] = [
  {
    id: 'room_00001',
    hotel_name: 'family mart',
    city: 'Tokyo',
    price_per_day: 1000,
    person: 2,
    description: '全家就是你家',
    picture_src:'https://bnextmedia.s3.hicloud.net.tw/image/album/2019-04/img-1555036406-19177@900.jpg',
  },
  {
    id: 'room_00002',
    hotel_name: '7-11',
    city: 'Tokyo',
    price_per_day: 1000,
    person: 4,
    description: 'always open, seven eleven',
    picture_src:'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AAIUqmO.img?h=0&w=720&m=6&q=60&u=t&o=f&l=f',
  },
  {
    id: 'room_00003',
    hotel_name: 'Mcdonald',
    city: 'NewYork',
    price_per_day: 1000,
    person: 5,
    description: '巴拉巴巴巴',
    picture_src:'https://media.bnextmedia.com.tw/image/album/2019-04/img-1554178414-23505.jpg',
  },
  {
    id: 'room_00004',
    hotel_name: 'family mart',
    city: 'Paris',
    price_per_day: 1000,
    person: 2,
    description: '全家就是你家',
    picture_src:'https://sw.cool3c.com/user/99257/2018/8351f02c-fbec-4210-8f73-1b5200c2b018.jpg',
  },
  {
    id: 'room_00005',
    hotel_name: 'family mart',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '全家就是你家',
    picture_src:'https://doqvf81n9htmm.cloudfront.net/data/himnbob_103/10/may/4/15_1920.jpg',
  },
  {
    id: 'room_00006',
    hotel_name: 'KFC',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '蛋塔專賣店',
    picture_src: 'https://s.yimg.com/ny/api/res/1.2/81FPUZoErBQZAONaereeUg--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9ODAw/https://media.zenfs.com/zh-tw/nownews.com/bc273f51fdb91f9d0edda01f2ec3d3a1',
  },
  {
    id: 'room_00007',
    hotel_name: 'MosBurger',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '摩絲漢堡',
    picture_src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Mos_Burger_Zhonghua_Store_20180616.jpg/450px-Mos_Burger_Zhonghua_Store_20180616.jpg',
  },
  {
    id: 'room_00008',
    hotel_name: 'Subway',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '潛艇堡',
    picture_src: 'https://image.cache.storm.mg/styles/smg-800x533-fp/s3/media/image/2019/01/22/20190122-075307_U5965_M493824_81f5.jpg?itok=GqGDagIX',
  },
  {
    id: 'room_00009',
    hotel_name: 'TheHouse',
    city: 'Taipei',
    price_per_day: 1000,
    person: 4,
    description: 'AAAAAAAA',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT9w67nJ04te6JesbNwiSb1CgKjeYANhHw6o7_KZhQwKtf0q25H&usqp=CAU',
  },
  {
    id: 'room_00010',
    hotel_name: 'TheHouse',
    city: 'NewYork',
    price_per_day: 1000,
    person: 3,
    description: 'YOOOOOOOO',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQPQhqGswjzzIq-AXRl-MOqg3H8MA1EpDmhUpZIzn-OGPhDm9i9&usqp=CAU',
  },
  {
    id: 'room_00011',
    hotel_name: 'KFC',
    city: 'Tokyo',
    price_per_day: 1000,
    person: 4,
    description: 'So good',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGnhG1LnFoG6TeT7vr8lAhxX6R8m9A9hrdsgu-y3_NCp0vu4CR&usqp=CAU',
  },
  {
    id: 'room_00012',
    hotel_name: 'Trivoga',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: 'Find hotel?',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQgMLOr8B7B4ViJ8Ya-0zeP1aAUnhvzo72JctpIrCLt4G4ShJuX&usqp=CAU',
  },
  {
    id: 'room_00013',
    hotel_name: 'Life',
    city: 'Taipei',
    price_per_day: 1000,
    person: 3,
    description: 'Hi Life',
    picture_src: 'https://s.yimg.com/ny/api/res/1.2/NEuyHbqWkxoGl2wE6IBZyw--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9MzIwO2g9MjQwO2lsPXBsYW5l/http://media.zenfs.com/zh_hant_tw/News/cardu/cardu_news_201701240005.jpg',
  },
  {
    id: 'room_00014',
    hotel_name: 'Life',
    city: 'Tokyo',
    price_per_day: 1000,
    person: 4,
    description: 'Yo Life',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRjRIDzuNHp4M2rZdQ97x5py-9SO8UdF_vxX457LFGb1URiBwe_&usqp=CAU',
  },
  {
    id: 'room_00015',
    hotel_name: 'RomanticDuke',
    city: 'Paris',
    price_per_day: 1000,
    person: 2,
    description: '找回屬於你的浪漫',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS2f4AKfyDYgNDfAfX9s46S1R9mWgSl9DAFsVgk2Yfum1_YEyWH&usqp=CAU',
  },
  {
    id: 'room_00016',
    hotel_name: 'BurgerKing',
    city: 'Taipei',
    price_per_day: 1000,
    person: 4,
    description: '火烤就是美味',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRJKeLihphturYo1ucaCmF-UlzkH1UiBdgle2OAFxZXkP4txCU_&usqp=CAU',
  },
  {
    id: 'room_00017',
    hotel_name: 'BurgerKing',
    city: 'Paris',
    price_per_day: 1000,
    person: 2,
    description: 'Roast!!!',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTucJgt_K0xoY1-oy9IJRbvZY3Lseh_EZUFad7p56v9MXMy5CX3&usqp=CAU',
  },
  {
    id: 'room_00018',
    hotel_name: 'SmileHouse',
    city: 'Tokyo',
    price_per_day: 1000,
    person: 2,
    description: ':)',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTKvFLlvALoxedfYOlESs4HSncvUSqs1pWWINl2BKv9WjwBbPYi&usqp=CAU',
  },
  {
    id: 'room_00019',
    hotel_name: 'DanceRoom',
    city: 'Taipei',
    price_per_day: 1000,
    person: 4,
    description: '要打去練舞室打',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ_zkPvVPZXngsL2QBh1KHKS0yFqRgEE2q4DNFTpsZYItlRzJCd&usqp=CAU',
  },{
    id: 'room_00020',
    hotel_name: '華府',
    city: 'Taipei',
    price_per_day: 1000,
    person: 6,
    description: '謝謝你9527',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcStIrml7lTxA9yoZw7GGTqCIVm5I4OuP8Kjm4omQPTWHa2OYuaP&usqp=CAU',
  },
  {
    id: 'room_00021',
    hotel_name: '蟹寶王',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '美味蟹堡',
    picture_src: 'https://www.adaymag.com/wp-content/uploads/2014/07/adaymag-restaurant-looks-like-krusty-krab-spongebob-squarepants-01.jpg',
  },
  {
    id: 'room_00022',
    hotel_name: '海之霸',
    city: 'Taipei',
    price_per_day: 1000,
    person: 4,
    description: '海霸棒',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0EqNpxK74-zCnwcewrGQ5jhouhwMg1HmRQsRC6kq89jsyJJUs&usqp=CAU',
  },
  {
    id: 'room_00023',
    hotel_name: '鳳梨屋',
    city: 'Paris',
    price_per_day: 1000,
    person: 3,
    description: 'Oh~~~~~',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQcX1J5_zzLoWz57zK5Exwbiu7RkKyZi03_uy_eVmDny-SkunUV&usqp=CAU',
  },
  {
    id: 'room_00024',
    hotel_name: '大石頭',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '派大星教授加博士先生',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR5KW6_NR10AToCBFmjHINccNYdg3tF_3kQ0EO8fZ__zYvuf7nA&usqp=CAU',
  },
  {
    id: 'room_00025',
    hotel_name: '富士山',
    city: 'Tokyo',
    price_per_day: 1000,
    person: 6,
    description: 'YAAAAAAA',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQCOTkrSRkvQSGRLIy_bBzv4oppWwQZG_q0uMjw4uOELPwmeumZ&usqp=CAU',
  },
  {
    id: 'room_00026',
    hotel_name: '陽明山',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '齁七逃',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQJicnpz_eeZ2mB2zynb6mIvSDdjI75sxgvIvdbKAe1yDjllDgZ&usqp=CAU',
  },
  {
    id: 'room_00027',
    hotel_name: '秋明山',
    city: 'Taipei',
    price_per_day: 1000,
    person: 3,
    description: 'Dejavu',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTp1qW3nLSAxvgvzTVJnqrRW0-m4MLj0nrVW2K1xfwjPS-gkBjD&usqp=CAU',
  },
  {
    id: 'room_00028',
    hotel_name: 'JoyHouse',
    city: 'Taipei',
    price_per_day: 1000,
    person: 4,
    description: 'Yeeeeeeee',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS2Lvf7dLOGXqTwsnKCsvPuq3E4o9R8sAFkAXSf9PBFSV2WTYnS&usqp=CAU',
  },
  {
    id: 'room_00029',
    hotel_name: '海砂屋',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: 'hello',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR_2KpWhImxdrVJb7qExVQxFTQhUcsqMQN7Zjd8T0wcOwoXWTXZ&usqp=CAU',
  },
  {
    id: 'room_00030',
    hotel_name: 'KFC',
    city: 'NewYork',
    price_per_day: 1000,
    person: 4,
    description: 'yummy',
    picture_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcScgU3ioqrGCRl3XfUvX83cmMmSec_Zvs62dLXOoqmBV9Hux5hp&usqp=CAU',
  },
]
