import { Hotel } from '../model'

export const hotelList: Hotel[] = [
  {
    id: 'room_00001',
    hotel_name: 'family mart',
    city: 'Tokyo',
    price_per_day: 1000,
    person: 2,
    description: '全家就是你家',
  },
  {
    id: 'room_00002',
    hotel_name: '7-11',
    city: 'Tokyo',
    price_per_day: 1000,
    person: 4,
    description: 'always open, seven eleven',
  },
  {
    id: 'room_00003',
    hotel_name: 'Mcdonald',
    city: 'NewYork',
    price_per_day: 1000,
    person: 5,
    description: '巴拉巴巴巴',
  },
  {
    id: 'room_00004',
    hotel_name: 'family mart',
    city: 'Paris',
    price_per_day: 1000,
    person: 2,
    description: '全家就是你家',
  },
  {
    id: 'room_00005',
    hotel_name: 'family mart',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '全家就是你家',
  },
  {
    id: 'room_00006',
    hotel_name: 'KFC',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '蛋塔專賣店',
  },
  {
    id: 'room_00007',
    hotel_name: 'MosBurger',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '摩絲漢堡',
  },
  {
    id: 'room_00008',
    hotel_name: 'Subway',
    city: 'Taipei',
    price_per_day: 1000,
    person: 2,
    description: '潛艇堡',
  },
]
